[package]
name = "drc-sim-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitter = "0.6.2"
log = { version = "0.4.21", features = ["std"] }
simple_logger = "4.3.3"
